### ISSUE TITLE
채팅방에서 방장이 시작하기 눌렀을 때 준비 되어있지 않은 상태 에러 표시하기

### ISSUE THREAD

**Issue by jaewoongs** [Team-Crops/fit-web#161]
<img width="1624" alt="image" src="https://github.com/Team-Crops/fit-web/assets/58589176/de8e3657-36a3-4a2b-a2b9-4c47239300a9">

모든 인원이 매칭 준비가 되지 않았습니다. alert으로 표시

**Comment by seheon99** [comment]
- #187
